### ISSUE TITLE
After the plugin_path change, can no longer converge

### ISSUE THREAD

**Issue by dimtruck** [mmi-cookbooks/chef-client#13]
After https://github.com/mmi-cookbooks/chef-client/commit/bcb5edc25054f8c643633e58e195db98221b107a

I'm getting

```
==> default:   * ruby_block[reload_client_config] action create
==> default: 
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'ruby_block[reload_client_config]'
==> default:     ================================================================================
==> default:     
==> default:     NoMethodError
==> default:     -------------
==> default:     
==> default: undefined method `plugin_path' for Ohai:Module
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/chef-client/recipes/config.rb:51:in `block (2 levels) in from_file'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:136:in `run_delayed_notification'
==> default:     
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:124:in `block in run_delayed_notifications'
==> default:     
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `each'
==> default:     
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `run_delayed_notifications'
==> default:     
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:113:in `converge'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/chef-client/recipes/config.rb
==> default:     
==> default:     
==> default:  49: ruby_block 'reload_client_config' do
==> default:     
==> default:  50:   block do
==> default:     
==> default:  51:     Chef::Config.from_file("#{node['chef_client']['conf_dir']}/client.rb")
==> default:     
==> default:  52:   end
==> default:     
==> default:  53:   action :nothing
==> default:     
==> default:  54: end
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/chef-client/recipes/config.rb:49:in `from_file'
==> default:     
==> default: 
==> default:     
==> default: ruby_block("reload_client_config") do
==> default:     
==> default:   action [:nothing]
==> default:     
==> default:   retries 0
==> default:     
==> default:   retry_delay 2
==> default:     
==> default:   default_guard_interpreter :default
==> default:     
==> default:   block_name "reload_client_config"
==> default:     
==> default:   declared_type :ruby_block
==> default:     
==> default:   cookbook_name "chef-client"
==> default:       recipe_name "config"
==> default:     
==> default:   block #<Proc:0x00000006ab41f8@/var/chef/cache/cookbooks/chef-client/recipes/config.rb:50>
==> default:     
==> default: end
```

**Comment by jjbuchan** [comment]
This also broken on staging branch:

From log0.dfw1.stage:
```
failed to handle resource --> :create ruby_block[reload_client_config]

undefined method `plugin_path' for Ohai:Module
chef client failed. 35 resources updated, took 47.34 seconds
```

**Comment by mburns** [comment]
fixed in staging...

**Comment by drenalin23** [comment]
After some manual testing it appears that 

ohai.plugin_path << '/etc/chef/ohai_plugins'

in /etc/chef/client.rb works in Chef > 12.8.1 but not in Chef < 12.4.3.  I haven't been able to determine at what version the change comes in but Metrics/MaaS are moving to 12.8.1.  When that is complete then version 0.1.10 should be available to be used.

**Comment by drenalin23** [comment]
https://github.com/racker/chef/pull/4193

**Comment by drenalin23** [comment]
Finally found it - https://github.com/chef-cookbooks/chef-client/search?utf8=%E2%9C%93&q=ohai_new_config_syntax

New format works with Ohai 8.6.0+  (not related directly to Chef version).

**Comment by dimtruck** [comment]
Hmm, I thought we were on 12.8.1 ... but you did mention > 12.8.1 so maybe it doesn't include that? 

https://github.com/racker/ele/blob/master/Vagrantfile#L95

**Comment by dimtruck** [comment]
Also, not sure where the version of ohai comes from but we're on the latest ohai cookbook version https://github.com/racker/chef/blob/master/Berksfile.lock#L84

**Comment by dimtruck** [comment]
(please excuse my ignorance ... I presume that chef-client dictates which ohai version we're using but I'm not sure 100%)

**Comment by drenalin23** [comment]
Ohai is bundled with chef - so usually you'll get ohai/chef-client of same versions on an upgrade.  Unfortunately we have different versions of chef-client and ohai in staging.

```
MMF2PTFD58:chef scot8709$ knife ssh -C 3 'name:*' 'ohai -v'
cass2.lon3.stage.cm.k1k.me      Ohai: 8.11.1
api1.ord1.stage.cm.k1k.me       Ohai: 8.7.0
log1.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
cass1.dfw1.stage.cm.k1k.me      Ohai: 8.11.1
cass0.lon3.stage.cm.k1k.me      Ohai: 8.11.1
scribe1.ord1.stage.cm.k1k.me    Ohai: 8.11.1
cass0.dfw1.stage.cm.k1k.me      Ohai: 8.11.1
collector1.ord1.stage.cm.k1k.me Ohai: 8.7.0
kafka0.ord1.stage.cm.k1k.me     Ohai: 8.11.1
scribe0.lon3.stage.cm.k1k.me    Ohai: 8.11.1
scribe1.lon3.stage.cm.k1k.me    Ohai: 8.11.1
cass1.lon3.stage.cm.k1k.me      Ohai: 8.11.1
cass3.dfw1.stage.cm.k1k.me      Ohai: 8.11.1
kafka1.dfw1.stage.cm.k1k.me     Ohai: 8.11.1
api1.dfw1.stage.cm.k1k.me       Ohai: 8.7.0
agent1.ord1.stage.cm.k1k.me     Ohai: 8.7.0
util0.lon3.stage.cm.k1k.me      Ohai: 8.11.1
cep0.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
cass2.ord1.stage.cm.k1k.me      Ohai: 8.11.1
messenger1.lon3.stage.cm.k1k.me Ohai: 8.7.0
kafka0.lon3.stage.cm.k1k.me     Ohai: 8.11.1
api0.lon3.stage.cm.k1k.me       Ohai: 8.7.0
collector1.lon3.stage.cm.k1k.me Ohai: 8.7.0
log2.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
messenger0.ord1.stage.cm.k1k.me Ohai: 8.7.0
collector1.dfw1.stage.cm.k1k.me Ohai: 8.7.0
messenger1.ord1.stage.cm.k1k.me Ohai: 8.7.0
messenger0.dfw1.stage.cm.k1k.me Ohai: 8.7.0
cep0.ord1.stage.cm.k1k.me       Ohai: 8.11.1
messenger1.dfw1.stage.cm.k1k.me Ohai: 8.7.0
collector0.lon3.stage.cm.k1k.me Ohai: 8.7.0
agent1.dfw1.stage.cm.k1k.me     Ohai: 8.7.0
cep0.lon3.stage.cm.k1k.me       Ohai: 8.11.1
cep1.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
cass1.ord1.stage.cm.k1k.me      Ohai: 8.11.1
kafka0.dfw1.stage.cm.k1k.me     Ohai: 8.11.1
agent0.lon3.stage.cm.k1k.me     Ohai: 8.7.0
collector0.ord1.stage.cm.k1k.me Ohai: 8.7.0
scribe0.ord1.stage.cm.k1k.me    Ohai: 8.11.1
cass2.dfw1.stage.cm.k1k.me      Ohai: 8.11.1
stats0.dfw1.stage.cm.k1k.me     Ohai: 8.7.0
api0.ord1.stage.cm.k1k.me       Ohai: 8.7.0
cep1.lon3.stage.cm.k1k.me       Ohai: 8.11.1
cass3.ord1.stage.cm.k1k.me      Ohai: 8.11.1
agent0.dfw1.stage.cm.k1k.me     Ohai: 8.11.1
log3.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
api0.dfw1.stage.cm.k1k.me       Ohai: 8.7.0
util0.ord1.stage.cm.k1k.me      Ohai: 8.11.1
messenger0.lon3.stage.cm.k1k.me Ohai: 8.7.0
agent1.lon3.stage.cm.k1k.me     Ohai: 8.7.0
log0.dfw1.stage.cm.k1k.me       Ohai: 8.11.1
scribe0.dfw1.stage.cm.k1k.me    Ohai: 8.11.1
util0.dfw1.stage.cm.k1k.me      Ohai: 8.11.1
cass0.ord1.stage.cm.k1k.me      Ohai: 8.11.1
kafka1.lon3.stage.cm.k1k.me     Ohai: 8.11.1
scribe1.dfw1.stage.cm.k1k.me    Ohai: 8.11.1
kafka1.ord1.stage.cm.k1k.me     Ohai: 8.11.1
agent0.ord1.stage.cm.k1k.me     Ohai: 8.7.0
cass3.lon3.stage.cm.k1k.me      Ohai: 8.11.1
collector0.dfw1.stage.cm.k1k.me Ohai: 8.7.0
cep1.ord1.stage.cm.k1k.me       Ohai: 8.11.1
api1.lon3.stage.cm.k1k.me       Ohai: 8.7.0
MMF2PTFD58:chef scot8709$ knife ssh -C 3 'name:*' 'chef-client -v'
cass2.lon3.stage.cm.k1k.me      Chef: 12.8.1
api1.ord1.stage.cm.k1k.me       Chef: 12.5.1
log1.dfw1.stage.cm.k1k.me       Chef: 12.8.1
cass0.lon3.stage.cm.k1k.me      Chef: 12.8.1
cass1.dfw1.stage.cm.k1k.me      Chef: 12.8.1
scribe1.ord1.stage.cm.k1k.me    Chef: 12.8.1
cass0.dfw1.stage.cm.k1k.me      Chef: 12.8.1
collector1.ord1.stage.cm.k1k.me Chef: 12.5.1
scribe0.lon3.stage.cm.k1k.me    Chef: 12.8.1
kafka0.ord1.stage.cm.k1k.me     Chef: 12.8.1
scribe1.lon3.stage.cm.k1k.me    Chef: 12.8.1
cass1.lon3.stage.cm.k1k.me      Chef: 12.8.1
cass3.dfw1.stage.cm.k1k.me      Chef: 12.8.1
kafka1.dfw1.stage.cm.k1k.me     Chef: 12.8.1
api1.dfw1.stage.cm.k1k.me       Chef: 12.5.1
agent1.ord1.stage.cm.k1k.me     Chef: 12.5.1
util0.lon3.stage.cm.k1k.me      Chef: 12.8.1
cass2.ord1.stage.cm.k1k.me      Chef: 12.8.1
cep0.dfw1.stage.cm.k1k.me       Chef: 12.8.1
kafka0.lon3.stage.cm.k1k.me     Chef: 12.8.1
messenger1.lon3.stage.cm.k1k.me Chef: 12.5.1
api0.lon3.stage.cm.k1k.me       Chef: 12.5.1
collector1.lon3.stage.cm.k1k.me Chef: 12.5.1
collector1.dfw1.stage.cm.k1k.me Chef: 12.5.1
log2.dfw1.stage.cm.k1k.me       Chef: 12.8.1
cep0.ord1.stage.cm.k1k.me       Chef: 12.8.1
messenger1.ord1.stage.cm.k1k.me Chef: 12.5.1
messenger0.ord1.stage.cm.k1k.me Chef: 12.5.1
messenger0.dfw1.stage.cm.k1k.me Chef: 12.5.1
messenger1.dfw1.stage.cm.k1k.me Chef: 12.5.1
collector0.lon3.stage.cm.k1k.me Chef: 12.5.1
kafka0.dfw1.stage.cm.k1k.me     Chef: 12.8.1
cep0.lon3.stage.cm.k1k.me       Chef: 12.8.1
agent1.dfw1.stage.cm.k1k.me     Chef: 12.5.1
cass1.ord1.stage.cm.k1k.me      Chef: 12.8.1
collector0.ord1.stage.cm.k1k.me Chef: 12.5.1
scribe0.ord1.stage.cm.k1k.me    Chef: 12.8.1
cass2.dfw1.stage.cm.k1k.me      Chef: 12.8.1
cep1.lon3.stage.cm.k1k.me       Chef: 12.8.1
api0.ord1.stage.cm.k1k.me       Chef: 12.5.1
cass3.ord1.stage.cm.k1k.me      Chef: 12.8.1
log3.dfw1.stage.cm.k1k.me       Chef: 12.8.1
stats0.dfw1.stage.cm.k1k.me     Chef: 12.5.1
agent0.dfw1.stage.cm.k1k.me     Chef: 12.8.1
api0.dfw1.stage.cm.k1k.me       Chef: 12.5.1
agent1.lon3.stage.cm.k1k.me     Chef: 12.5.1
util0.ord1.stage.cm.k1k.me      Chef: 12.8.1
messenger0.lon3.stage.cm.k1k.me Chef: 12.5.1
scribe0.dfw1.stage.cm.k1k.me    Chef: 12.8.1
util0.dfw1.stage.cm.k1k.me      Chef: 12.8.1
log0.dfw1.stage.cm.k1k.me       Chef: 12.8.1
scribe1.dfw1.stage.cm.k1k.me    Chef: 12.8.1
cass0.ord1.stage.cm.k1k.me      Chef: 12.8.1
kafka1.lon3.stage.cm.k1k.me     Chef: 12.8.1
kafka1.ord1.stage.cm.k1k.me     Chef: 12.8.1
agent0.ord1.stage.cm.k1k.me     Chef: 12.5.1
cass3.lon3.stage.cm.k1k.me      Chef: 12.8.1
cep1.ord1.stage.cm.k1k.me       Chef: 12.8.1
cep1.dfw1.stage.cm.k1k.me       Chef: 12.8.1
collector0.dfw1.stage.cm.k1k.me Chef: 12.5.1
api1.lon3.stage.cm.k1k.me       Chef: 12.5.1
agent0.lon3.stage.cm.k1k.me     Chef: 12.5.1
```

**Comment by drenalin23** [comment]
You will note though that we are over 8.6.0.  I now noticed that the fix I committed to fix the case from 

Ohai.plugin_path to ohai.plugin_path 

was not in the 1.0.10 tagged version.  The chef documentation for client.rb incorrectly listed the upper case Ohai (although the current chef-client supermarket cookbook shows the correct casing).  I will fix later today.

**Comment by drenalin23** [comment]
https://github.com/mmi-cookbooks/chef-client/pull/15
https://github.com/chef/chef-web-docs/pull/249

**Comment by drenalin23** [comment]
This is fixed by https://github.com/racker/chef/issues/4216
